apiVersion: batch/v1
kind: Job
metadata:
  name: mailer-migration-1
  namespace: test
spec:
  ttlSecondsAfterFinished: 300 # 5 minutes
  template:
    spec:    
      containers:
      - image: crispyduck/covle-mailer:latest
        name: mailer-migration
        command: ["node", "node_modules/db-migrate/bin/db-migrate", "up"]
        env:
        - name: DB_HOST
          value: db-cluster
        - name: DB_PORT
          value: "25060"
        - name: DB_NAME
          value: test-mailer
        - name: DB_USER
          value: test-mailer
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-password
              key: mailer
      imagePullSecrets:
      - name: regcred
      restartPolicy: Never
